from .ItemLevel import DAZARALOR
from .ItemLevel import M_PLUS_ITEMLEVEL
from .ItemLevel import TITANFORGING_CUT_OFF
from .ItemLevel import DARKSHORE

dungeon = [
    "Ashvane Warden's Cuirass",
    "Breastplate of Arterial Protection",
    "Breastplate of the Vengeful",
    "Chestguard of the Deep Denizen",
    "Desert Guardian's Breastplate",
    "Harpooner's Plate Cuirass",
    "C'thraxxi Binders Pauldrons",
    "Kraken Shell Pauldrons",
    "Lockjaw Shoulderplate",
    "Pauldrons of the Great Unifier",
    "Pauldrons of the Horned Horror",
    "Skyscorcher Pauldrons",
    "Greathelm of the Putrid Path",
    "Helm of Abyssal Malevolence",
    "Helm of the Raptor King",
    "Overseer's Riot Helmet",
    "Sea-Brawler's Greathelm",
    "Soulspun Casque",
    "Corrupted Hexxer's Vestments",
    "Deathslaver's Hauberk",
    "Hauberk of Sunken Despair",
    "Loa-Blessed Chestguard",
    "Shrapnel-Dampening Chestguard",
    "Tri-Heart Chestguard",
    "Coif of the Court Spider",
    "Hood of the Dark Reaper",
    "Sethraliss' Fanged Helm",
    "Soulscarred Headgear",
    "Sweete's Jeweled Headgear",
    "Visage of Bloody Horrors",
    "Amalgamated Abomination Spaulders",
    "Cannoneer's Mantle",
    "Crashguard Spaulders",
    "Gaping Maw Shoulderguard",
    "Hook-Barbed Spaulders",
    "Spaulders of Prime Emperor",
    "Cephalohide Jacket",
    "Gore-Splattered Vest",
    "Raiment of the Blighted Tribe",
    "Spymaster's Wrap",
    "Venture Co. Plenipotentiary Vest",
    "Vest of Reverent Adoration",
    "Circlet of the Enveloping Leviathan",
    "Cowl of Fluid Machinations",
    "Flashpowder Hood",
    "High Altitude Turban",
    "Hood of the Slithering Loa",
    "Irontide Captain's Hat",
    "Gold-Tasseled Epaulets",
    "Gorak Tul's Mantle",
    "Mantle of Fastidious Machinations",
    "Pistoleer's Spaulders",
    "Shoulders of the Sanguine Monstrosity",
    "Tentacle-Laced Spaulders",
    "Blood-Drenched Robes",
    "Inmate's Straight Robe",
    "Loa Betrayer's Vestments",
    "Petticoat of the Self-Stylized Azerite Baron",
    "Robes of the Reborn Serpent",
    "Ruffled Poet Blouse",
    "Grasping Crown of the Deep",
    "Headdress of the First Empire",
    "Secret Spinner's Miter",
    "Smartly Plumed Cap",
    "Soulfuel Headdress",
    "Stormlurker's Cowl",
    "Amice of the Returned",
    "Brood Cleanser's Amice",
    "Exquisitely Aerodynamic Shoulderpads",
    "Mantle of Ceremonial Ascension",
    "Mantle of Void-Touched Waters",
    "Pauldrons of Vile Corruption",
]

dazaralor = [
    "Breastplate of Divine Purification",
    "Breastplate of the Deathbound",
    "Sea Swell Chestplate",
    "Dyno-Sprocket Spaulders",
    "Ridgeplate Pauldrons",
    "Spaulders of the Gorilla King",
    "Crown of Bloody Succession",
    "Glaciercrest Helm",
    "Helm of Tempered Jade",
    "Flag Officer's Overcoat",
    "Gonk's Scale Robes",
    "Mistfire Raiment",
    "Electrified Crown of Rahu'ai",
    "Simian Berserker's Helm",
    "Target-Tracking Headgear",
    "Mantle of the Soulbinder's Caress",
    "Pauldrons of Ancestral Vengeance",
    "Tidal Shroud Spaulders",
    "Grongpelt Vest",
    "Mekkatorque's Bomber Jacket",
    "Vestments of Indomitable Will",
    "Cowl of Righteous Resolve",
    "Crown of A'akul's Dark Reign",
    "Tidemother's Cover",
    "Admiralty's Ceremonial Epaulets",
    "Ma'ra's Boneblade Mantle",
    "Mestrah's Singing Spaulders",
    "Phantom Stalker Shoulders",
    "Divine Fury Raiment",
    "Robes of Biting Cold",
    "Vestments of the Afterlife",
    "Blazewing Hood",
    "Cowl of Tideborne Omens",
    "Crown of the Seducer",
    "Bristling Fur-Lined Amice",
    "Giga-Charged Shoulderpads",
    "Mantle of the Skyterror",
]

darkshore = [
    "Petrified Ironbark Crown",
    "Forest Protector's Shoulderguards",
    "Warring Ancient's Crown",
    "Warring Ancient's Mask",
    "Garments of the Forest Lord",
]

itemlevel_dict = {
    "Chestguard of Virulent Mutagens": 385,
    "Chestplate of Apocalyptic Machinations": 385,
    "Chitinspine Pauldrons": 385,
    "Gridrunner Galea": 385,
    "Helm of the Defiled Laboratorium": 385,
    "C'thraxxi General's Hauberk": 385,
    "Chainvest of Assured Quality": 385,
    "Crest of the Undying Visionary": 385,
    "Flame-Sterilized Spaulders": 385,
    "Spaulders of Coagulated Viscera": 385,
    "Jerkin of the Aberrant Chimera": 385,
    "Tunic of the Sanguine Deity": 385,
    "Cowl of Dark Portents": 385,
    "Hood of Pestilent Ichor": 385,
    "Usurper's Bloodcaked Spaulders": 385,
    "Robes of the Unraveler": 385,
    "Crown of the Seducer": 385,
    "Visage of the Ascended Prophet": 385,
    "Amice of Corrupting Horror": 385,
    "Mantle of Contained Corruption": 385,
    "Molded War Machine Grill": 370,
    "Polished Shieldbearer's Breastplate": 370,
    "Lion's Roar Pauldrons": 370,
    "Spiked Dreadshield Pauldrons": 370,
    "Stormcrash Chestguard": 355,
    "Ice-Carved Shoulderplates": 355,
    "Petrified Mask of the Afterlife": 355,
    "Spaulders of the Enveloping Maw": 355,
    "Feathered Galeforce Crest": 355,
    "Hailstone Hauberk": 355,
    "Scalemail Battle Harness": 370,
    "Sharpshooter's Chainmail Hauberk": 370,
    "Alliance Bowman's Coif": 370,
    "Warscout's Horned Helm": 370,
    "Dire-Tooth Spaulders": 370,
    "Gilded-Wing Shoulderguards": 370,
    "Vest of the Veiled Gryphon": 370,
    "Doom's Howl Vest": 370,
    "Chestguard of Dire Winds": 355,
    "Hood of the Sinuous Devilsaur": 355,
    "Deathshambler's Shoulderpads": 355,
    "Raider's Shrouding Thobe": 355,
    "Matriarch's Shadowveil": 355,
    "Amice of the Rending Abyss": 355,
    "Battlemage's Collar": 370,
    "Warcaster's Arcane Mantle": 370,
    "Warcaster's Doom Mantle": 370,
}

for item in dungeon:
    itemlevel_dict[item] = M_PLUS_ITEMLEVEL + TITANFORGING_CUT_OFF

for item in dazaralor:
    itemlevel_dict[item] = DAZARALOR

for item in darkshore:
    itemlevel_dict[item] = DARKSHORE

pvp_examples = {
    'Dread': 385,
    'Notorious': 430,
    'Sinister': 415,
}
