import enum


class Expansion(int, enum.Enum):
    CLASSIC = 0
    BURNING_CRUSADE = 1
    WRATH_OF_THE_LICHKING = 2
    CATACLYSM = 3
    PANDARIA = 4
    WARLORDS_OF_DRAENOR = 5
    LEGION = 6
    BATTLE_FOR_AZEROTH = 7
    SHADOWLANDS = 8
    DRAGONFLIGHT = 9
    THE_WAR_WITHIN = 10
    UNKNOWN_MINUS_3 = -3
