races = {
    "alliance": {
        "draenei": (
            "warrior",
            "paladin",
            "hunter",
            "priest",
            "shaman",
            "mage",
            "monk",
            "death_knight",
        ),
        "dwarf": (
            "warrior",
            "paladin",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        ),
        "gnome": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        ),
        "human": (
            "warrior",
            "paladin",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        ),
        "night_elf": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "monk",
            "druid",
            "death_knight",
            "demon_hunter",
        ),
        "pandaren": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "monk",
            "death_knight",
        ),
        "worgen": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "warlock",
            "druid",
            "death_knight",
        ),
        "void_elf": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        ),
        "lightforged_draenei": (
            "warrior",
            "paladin",
            "hunter",
            "priest",
            "mage",
            "death_knight",
        ),
        "dark_iron_dwarf": (
            "warrior",
            "paladin",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        ),
        "kul_tiran": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "monk",
            "druid",
            "death_knight",
        ),
        "mecha_gnome": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        )
    },
    "horde": {
        "blood_elf": (
            "warrior",
            "paladin",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "warlock",
            "monk",
            "death_knight",
            "demon_hunter",
        ),
        "goblin": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "warlock",
            "death_knight",
        ),
        "orc": (
            "warrior",
            "hunter",
            "rogue",
            "shaman",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        ),
        "pandaren": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "monk",
            "death_knight",
        ),
        "tauren": (
            "warrior",
            "paladin",
            "hunter",
            "priest",
            "shaman",
            "monk",
            "druid",
            "death_knight",
        ),
        "troll": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "warlock",
            "monk",
            "druid",
            "death_knight",
        ),
        "undead": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        ),
        "nightborne": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        ),
        "highmountain_tauren": (
            "warrior",
            "hunter",
            "shaman",
            "monk",
            "druid",
            "death_knight",
        ),
        "maghar_orc": (
            "warrior",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "monk",
            "death_knight",
        ),
        "zandalari_troll": (
            "warrior",
            "paladin",
            "hunter",
            "rogue",
            "priest",
            "shaman",
            "mage",
            "monk",
            "druid",
            "death_knight",
        ),
        "vulpera": (
            "warrior",
            "hunter",
            "priest",
            "shaman",
            "mage",
            "warlock",
            "monk",
            "death_knight",
        )
    }
}

translations = {
    "draenei": {
        'en_US': 'Draenei',
        'it_IT': 'Draenei',
        'de_DE': 'Draenei',
        'fr_FR': 'Draeneï',
        'ru_RU': 'Дреней',
        'es_ES': 'Draenei',
        'ko_KR': '드레나이',
        'cn_CN': '德莱尼'
    },
    "dwarf": {
        'en_US': 'Dwarf',
        'it_IT': 'Nano',
        'de_DE': 'Zwerg',
        'fr_FR': 'Nain',
        'ru_RU': 'Дворф',
        'es_ES': 'Enano',
        'ko_KR': '드워프',
        'cn_CN': '矮人'
    },
    "gnome": {
        'en_US': 'Gnome',
        'it_IT': 'Gnomo',
        'de_DE': 'Gnom',
        'fr_FR': 'Gnome',
        'ru_RU': 'Гном',
        'es_ES': 'Gnomo',
        'ko_KR': '노움',
        'cn_CN': '侏儒'
    },
    "human": {
        'en_US': 'Human',
        'it_IT': 'Umano',
        'de_DE': 'Mensch',
        'fr_FR': 'Humain',
        'ru_RU': 'Человек',
        'es_ES': 'Humano',
        'ko_KR': '인간',
        'cn_CN': '人类'
    },
    "night_elf": {
        'en_US': 'Night Elf',
        'it_IT': 'Elfo della Notte',
        'de_DE': 'Nachtelf',
        'fr_FR': 'Elfe de la nuit',
        'ru_RU': 'Ночной эльф',
        'es_ES': 'Elfo de la noche',
        'ko_KR': '나이트 엘프',
        'cn_CN': '暗夜精灵'
    },
    "worgen": {
        'en_US': 'Worgen',
        'it_IT': 'Worgen',
        'de_DE': 'Worgen',
        'fr_FR': 'Worgen',
        'ru_RU': 'Ворген',
        'es_ES': 'Huargen',
        'ko_KR': '늑대인간',
        'cn_CN': '狼人'
    },
    "void_elf": {
        'en_US': 'Void Elf',
        'it_IT': 'Elfo del Vuoto',
        'de_DE': 'Leerenelf',
        'fr_FR': 'Elfe du Vide',
        'ru_RU': 'Эльф Бездны',
        'es_ES': 'Elfo del Vacío',
        'ko_KR': '공허 엘프',
        'cn_CN': '虚空精灵'
    },
    "lightforged_draenei": {
        'en_US': 'Lightforged Draenei',
        'it_IT': 'Draenei Forgialuce',
        'de_DE': 'Lichtgeschmiedeter Draenei',
        'fr_FR': 'Draeneï sancteforge',
        'ru_RU': 'Озаренный дреней',
        'es_ES': 'Draenei forjado por la Luz',
        'ko_KR': '빛벼림 드레나이',
        'cn_CN': '光铸德莱尼'
    },
    "dark_iron_dwarf": {
        'en_US': 'Dark Iron Dwarf',
        'it_IT': 'Nano Ferroscuro',
        'de_DE': 'Dunkeleisenzwerg',
        'fr_FR': 'Nain sombrefer',
        'ru_RU': 'Дворф из клана Черного Железа',
        'es_ES': 'Enano Hierro Negro',
        'ko_KR': '검은무쇠 드워프',
        'cn_CN': '黑铁矮人'
    },
    "blood_elf": {
        'en_US': 'Blood Elf',
        'it_IT': 'Elfo del Sangue',
        'de_DE': 'Blutelf',
        'fr_FR': 'Elfe de sang',
        'ru_RU': 'Эльф крови',
        'es_ES': 'Elfo de sangre',
        'ko_KR': '블러드 엘프',
        'cn_CN': '血精灵'
    },
    "goblin": {
        'en_US': 'Goblin',
        'it_IT': 'Goblin',
        'de_DE': 'Goblin',
        'fr_FR': 'Gobelin',
        'ru_RU': 'Гоблин',
        'es_ES': 'Goblin',
        'ko_KR': '고블린',
        'cn_CN': '地精'
    },
    "orc": {
        'en_US': 'Orc',
        'it_IT': 'Orco',
        'de_DE': 'Orc',
        'fr_FR': 'Orc',
        'ru_RU': 'Орк',
        'es_ES': 'Orco',
        'ko_KR': '오크',
        'cn_CN': '兽人'
    },
    "pandaren": {
        'en_US': 'Pandaren',
        'it_IT': 'Pandaren',
        'de_DE': 'Pandaren',
        'fr_FR': 'Pandaren',
        'ru_RU': 'Пандарен',
        'es_ES': 'Pandaren',
        'ko_KR': '판다렌',
        'cn_CN': '熊猫人'
    },
    "tauren": {
        'en_US': 'Tauren',
        'it_IT': 'Tauren',
        'de_DE': 'Tauren',
        'fr_FR': 'Tauren',
        'ru_RU': 'Таурен',
        'es_ES': 'Tauren',
        'ko_KR': '타우렌',
        'cn_CN': '牛头人'
    },
    "troll": {
        'en_US': 'Troll',
        'it_IT': 'Troll',
        'de_DE': 'Troll',
        'fr_FR': 'Troll',
        'ru_RU': 'Тролль',
        'es_ES': 'Trol',
        'ko_KR': '트롤',
        'cn_CN': '巨魔'
    },
    "undead": {
        'en_US': 'Undead',
        'it_IT': 'Non Morto',
        'de_DE': 'Untoter',
        'fr_FR': 'Mort-vivant',
        'ru_RU': 'Нежить',
        'es_ES': 'No-muerto',
        'ko_KR': '언데드',
        'cn_CN': '亡灵'
    },
    "nightborne": {
        'en_US': 'Nightborne',
        'it_IT': 'Nobile Oscuro',
        'de_DE': 'Nachtgeborener',
        'fr_FR': 'Sacrenuit',
        'ru_RU': 'Ночнорожденный',
        'es_ES': 'Nocheterna',
        'ko_KR': '나이트본',
        'cn_CN': '夜之子'
    },
    "highmountain_tauren": {
        'en_US': 'Highmountain Tauren',
        'it_IT': 'Tauren di Alto Monte',
        'de_DE': 'Hochbergtauren',
        'fr_FR': 'Tauren de Haut-Roc',
        'ru_RU': 'Таурен Крутогорья',
        'es_ES': 'Tauren Monte Alto',
        'ko_KR': '높은산 타우렌',
        'cn_CN': '至高岭牛头人'
    },
    "maghar_orc": {
        'en_US': "Mag'har Orc",
        'it_IT': "Orco Mag'har",
        'de_DE': "Mag'har",
        'fr_FR': 'Orc mag’har',
        'ru_RU': "Маг'хар",
        'es_ES': "Orco Mag'har",
        'ko_KR': '마그하르 오크',
        'cn_CN': '玛格汉兽人'
    }
}
