BEASTLORD = "beastlord"
DUNGEONSLICE = "dungeonslice"
HEAVYMOVEMENT = "heavymovement"
HECTICADDCLEAVE = "hecticaddcleave"
HELTERSKELTER = "helterskelter"
LIGHTMOVEMENT = "lightmovement"
PATCHWERK = "patchwerk"

FIGHTSTYLES = (
    BEASTLORD,
    DUNGEONSLICE,
    HEAVYMOVEMENT,
    HECTICADDCLEAVE,
    HELTERSKELTER,
    LIGHTMOVEMENT,
    PATCHWERK,
)
